// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var OtherComponent = require("./OtherComponent.bs.js");
var Core = require("@material-ui/core");

function Demo(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(OtherComponent.make, {
                  name: "Sergey",
                  age: 35,
                  status: /* Available */0,
                  team: "Delta"
                }), React.createElement(Core.Typography, {
                  children: "Some Text"
                }), React.createElement("div", undefined, "Hello World"));
}

var make = Demo;

exports.make = make;
/* react Not a pure module */
