// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function OtherComponent(Props) {
  var name = Props.name;
  var age = Props.age;
  var $$location = Props.location;
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, name), React.createElement("div", undefined, String(age)), React.createElement("div", undefined, Belt_Option.getWithDefault($$location, "no location")));
}

var make = OtherComponent;

exports.make = make;
/* react Not a pure module */
